# Generated by Django 3.1.7 on 2022-03-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armylist',
            name='points',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
