# Generated by Django 3.1.7 on 2022-03-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_armylist_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armylist',
            name='points',
        ),
    ]
