# Generated by Django 3.1.7 on 2022-03-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_remove_armylist_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='armylist',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
