# Generated by Django 3.1.7 on 2022-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_auto_20220328_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armylist',
            name='country',
            field=models.CharField(max_length=63),
        ),
    ]
