# Generated by Django 4.0.5 on 2022-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_remove_armylist_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armylist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
